---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6011/eureka/
---
spring:
  profiles: eurekasubject
#words: I,You,He,She,It
words: I,You,He,She,It
---
spring:
  profiles: eurekaverb
words: ran,knew,had,saw,bought
